### ISSUE TITLE
How to desactivate Safe For Work image generation ?

### ISSUE THREAD

**Issue by lbarasc** [illescasDaniel/ImageDreamer-QT-QUICK-MVC#1]
hi,
thank you for your software, it's really great but i want to use it without limit.
How to desactivate Safe For Work image generation ?

**Comment by illescasDaniel** [comment]
Hello! Sure, that's easy, simply set "__UNSAFE_IMAGE_DETECTOR_ENABLED: bool" to False in the repository model file and you might also want to change the model itself to the generic non-safe version (see the private __MODEL_OR_PATH property, just put the hugging face generic model url instead).


I will keep the public version of this app as it is, but feel free to download the code and change these settings by yourself. 👍🏼

I will close this thread for now.

**Comment by lbarasc** [comment]
Hello, thanks you for your answer, i don't have a high level of python and i think i cannot recompile your software without unsafe at False. can you recompile it with unsafe paramater ? thank you very much.
